### ISSUE TITLE
Display error character set

### ISSUE THREAD

**Issue by hc123asdf** [microsoft/azure-devops-intellij#387] opened 2020-08-21 06:23 UTC
The update and show history commands are show bad charset. It is normal to use TF or vs
idea version 2020.1   
plugin version  com.microsoft.vso.idea-1.160.0
tee version 14.134.00
[error img](http://testing.hongyangcloud.com/tts/2.png)
[noraml img](http://testing.hongyangcloud.com/tts/3.png)

**Comment by ForNeVeR** [comment] 2020-08-21 06:44
Hi! I believe, the same (or maybe similar) issue has already been reported as #311. Non-latin charsets are definitely broken right now. Hopefully, we'll be able to fix them eventually.

I'll go ahead and close this as a duplicate of #311, and will try to raise priority on #311.

**Closed by ForNeVeR** 2020-08-21 06:44 UTC
