### ISSUE TITLE
Still authentication issues when pushing to remote

### ISSUE THREAD

**Issue by Tom4U** [microsoft/azure-devops-intellij#209] opened 2019-06-14 12:29 UTC
After release of 1.152.0 authentication in general is working now. I can see my work items and such.

But if trying to push to the remote repository from inside Rider it's not working. Actually it's the same behaviour as it was previously (before 1.152.0), but this time only for pushing.

=== System Information ===
Build version: JetBrains Rider 2019.1.2 Build #RD-191.7141.355 June 5, 2019
Java version: 1.8.0_202-release-1483-b58amd64
Operating System: Windows 10 (10.0, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== Plugins ===
Custom plugins: [Ideolog (191.0.12.0), Azure DevOps (1.152.0), Angular Component Folding (1.4.1), .ignore (3.1.2.191), Rider Xamarin Android Support (191.7141.355), Markdown support (191.7141.32), Azure Toolkit for Rider (3.20.0.486-2019.1), Angular CLI QuickSwitch (1.3), TestLinker (2019.1.0)]
Disabled plugins:[CVS Integration (191.7141.355), Perforce Integration (191.7141.355), Subversion (191.7141.355), F# Support (2019.1.112), Mercurial Integration (191.7141.355), Stylus support (191.7141.355), Pug (ex-Jade) (191.7141.355), Unity Support (2019.1.0.110)]

==== Toolset ====
BuildTool: DotNetCoreMsBuild 16.0 (C:\Program Files\dotnet\sdk\2.2.300\MSBuild.dll)
MonoRuntime: <NONE>
.NET Core SDK CLI: C:\Program Files\dotnet\dotnet.exe
.NET Core SDK: 2.2.300(2.1.602;2.1.604;2.1.700;2.2.204;2.2.300)

==== IDE/Backend ====
WorkingSet/PrivateMem/ManagedMem: 91/612/210 MB
GC(0/1/2|LOH): 2191/645/49|27

==== Network ====
Accepted certificates: 0
Rejected certificates: 0

==== Stacktrace ====
> getAuthenticationInfoAsync failed
>
> com.microsoft.alm.plugin.exceptions.TeamServicesException: KEY_VSO_AUTH_FAILED
>	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:100)
>	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:69)
>	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
>	at com.microsoft.alm.plugin.idea.git.extensions.TfGitHttpAuthDataProvider.getAuthData(TfGitHttpAuthDataProvider.java:69)
>	at git4idea.remote.GitHttpAuthDataProvider.getAuthData(GitHttpAuthDataProvider.java:41)
>	at git4idea.commands.GitHttpGuiAuthenticator$ExtensionAdapterProvider.getData(GitHttpGuiAuthenticator.java:263)
>	at git4idea.commands.GitHttpGuiAuthenticator.lambda$askUsername$2(GitHttpGuiAuthenticator.java:134)
>	at git4idea.commands.GitPassthroughAuthenticationGate.waitAndCompute(GitAuthenticationGates.kt:52)
>	at git4idea.commands.GitHttpGuiAuthenticator.askUsername(GitHttpGuiAuthenticator.java:128)
>	at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.lambda$askUsername$0(GitHttpAuthService.java:65)
>	at git4idea.commands.GitHttpAuthService.getDefaultValueIfCancelled(GitHttpAuthService.java:78)
>	at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.askUsername(GitHttpAuthService.java:65)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.lang.reflect.Method.invoke(Method.java:498)
>	at org.jetbrains.ide.XmlRpcServerImpl.invoke(XmlRpcServerImpl.java:180)
>	at org.jetbrains.ide.XmlRpcServerImpl.invokeHandler(XmlRpcServerImpl.java:141)
>	at org.jetbrains.ide.XmlRpcServerImpl.process(XmlRpcServerImpl.java:101)
>	at org.jetbrains.ide.XmlRpcServerImpl$XmlRpcRequestHandler.process(XmlRpcServerImpl.java:58)
>	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:27)
>	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:42)
>	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
>	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11)
>	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:20)
>	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
>	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:133)
>	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:80)
>	at org.jetbrains.io.Decoder.channelRead(Decoder.java:38)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
>	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
>	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
>	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
>	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
>	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
>	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
>	at java.lang.Thread.run(Thread.java:748)

**Comment by ForNeVeR** [comment] 2019-06-14 13:07
Thank you for reporting this. Could you please show your git remote URL? In terminal:

```
git remote show origin
```

I'm interested in whether it has `username@` attached or not, and if it SSH or HTTPS.

**Comment by nexxbizdev** [comment] 2019-06-14 14:15
Same here:
======
Rider 2019.1.2
Azure DevOps plugin 1.1.52.0
======
getAuthenticationInfoAsync failed

com.microsoft.alm.plugin.exceptions.TeamServicesException: KEY_VSO_AUTH_FAILED
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:100)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:69)
	at com.microsoft.alm.plugin.idea.common.ui.common.LookupHelper.authenticateAndLoadVsoContexts(LookupHelper.java:158)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.VsoCheckoutPageModel.loadRepositories(VsoCheckoutPageModel.java:79)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutPageController.actionPerformed(CheckoutPageController.java:92)
	at com.microsoft.alm.plugin.idea.common.ui.controls.Hyperlink.notifyActionListeners(Hyperlink.java:91)
	at com.microsoft.alm.plugin.idea.common.ui.controls.Hyperlink.access$000(Hyperlink.java:25)
	at com.microsoft.alm.plugin.idea.common.ui.controls.Hyperlink$1.linkSelected(Hyperlink.java:35)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:356)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:330)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:706)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1646)
	at com.microsoft.alm.plugin.idea.common.ui.common.BaseDialogImpl.showModalDialog(BaseDialogImpl.java:185)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutController.showModalDialog(CheckoutController.java:75)
	at com.microsoft.alm.plugin.idea.git.extensions.GitCheckoutProvider.doCheckout(GitCheckoutProvider.java:39)
	at com.intellij.openapi.vcs.checkout.CheckoutAction.actionPerformed(CheckoutAction.java:29)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:252)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:200)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:190)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:184)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1416)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3080)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:159)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:111)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1412)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:306)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:279)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:136)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:105)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:214)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:105)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:442)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:395)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:341)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:299)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:501)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:555)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Tom4U** [comment] 2019-06-14 14:24
> git remote show origin

It's like: `https://dev.azure.com/[ORG]/[PROJECT]/_git/[PROJECT]`

**Comment by nexxbizdev** [comment] 2019-06-14 14:28
> git remote show origin

 Fetch URL:  https://*******@dev.azure.com/organization/project/_git/my_gitproject

**Comment by nexxbizdev** [comment] 2019-06-14 14:29
2019-06-14
16:25	Git Pull Failed
			Invocation failed Server returned invalid Response.
			java.lang.RuntimeException: Invocation failed Server returned invalid Response.
			at org.jetbrains.git4idea.http.GitAskPassXmlRpcClient.askPassword(GitAskPassXmlRpcClient.java:65)
			at org.jetbrains.git4idea.http.GitAskPassApp.main(GitAskPassApp.java:68)
			Caused by: java.io.IOException: Server returned invalid Response.
			at org.apache.xmlrpc.LiteXmlRpcTransport.sendRequest(LiteXmlRpcTransport.java:242)
			at org.apache.xmlrpc.LiteXmlRpcTransport.sendXmlRpc(LiteXmlRpcTransport.java:90)
			at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:72)
			at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
			at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
			at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178)
			at org.jetbrains.git4idea.http.GitAskPassXmlRpcClient.askPassword(GitAskPassXmlRpcClient.java:62)
			... 1 more
			Authentication failed for 'https://... (show balloon)

16:26	Fetch Failed
			Invocation failed Server returned invalid Response.
			java.lang.RuntimeException: Invocation failed Server returned invalid Response.
			at org.jetbrains.git4idea.http.GitAskPassXmlRpcClient.askPassword(GitAskPassXmlRpcClient.java:65)
			at org.jetbrains.git4idea.http.GitAskPassApp.main(GitAskPassApp.java:68)
			Caused by: java.io.IOException: Server returned invalid Response.
			at org.apache.xmlrpc.LiteXmlRpcTransport.sendRequest(LiteXmlRpcTransport.java:242)
			at org.apache.xmlrpc.LiteXmlRpcTransport.sendXmlRpc(LiteXmlRpcTransport.java:90)
			at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:72)
			at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
			at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
			at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178)
			at org.jetbrains.git4idea.http.GitAskPassXmlRpcClient.askPassword(GitAskPassXmlRpcClient.java:62)
			... 1 more
			Authentication failed for 'https://*******@dev.azure.com/organization/project/_git/my_gitproject... (show balloon)

**Comment by ForNeVeR** [comment] 2019-06-15 07:08
@Tom4U with remote URL such as yours, this looks as a duplicate of #205, and I guess we'll have to raise priority on that and fix it ASAP.

How did you got this remote URL? Usually, the Azure DevOps plugin and Azure DevOps web portal constructs URLs starting with `username@`. Seing URL without a `username@` is a bit unusual.

Also, the workaround for now would be to update your URL to contain the `username@` at the beginning, such as `https://[USERNAME]@dev.azure.com/[ORG]/[PROJECT]/_git/[PROJECT]`

**Comment by ForNeVeR** [comment] 2019-06-17 04:48
@nexxbizdev your case looks unusual. Could you please compress your logs (**Help | Compress Logs and Show in File Manager** in IDE) and send them to `ivan.migalev@jetbrains.com`?

**Comment by Tom4U** [comment] 2019-06-17 13:31
> 
> 
> @Tom4U with remote URL such as yours, this looks as a duplicate of #205, and I guess we'll have to raise priority on that and fix it ASAP.
> 
> How did you got this remote URL? Usually, the Azure DevOps plugin and Azure DevOps web portal construct URLs starting with `username@`. Seing URL without a `username@` is a bit unusual.
> 
@ForNeVeR I have no idea anymore how I added the remote address. But changing it to the format `https://[ORG]@dev.azure.com/[ORG]/[PROJECT]_git/[PROJECT]` as provided by Azure DevOps, pushing to remote now works.

So it's not the username I need here, but it seems the organization name instead.

I'll leave it to you / the team, if you like to close this issue here. But from my side, I'm fine with the format thing, as it's the address you get from DevOps.

**Comment by nexxbizdev** [comment] 2019-06-17 15:46
@ForNeVer does fetch and pull work as well? In my case push works fine, checking out new branches works fine as well, however, fetch and pull throws the exception as described. 

I'll compress the log files soon and send it to Ivan

**Comment by ForNeVeR** [comment] 2019-06-18 05:18
@nexxbizdev for me, both pull and push were working alright. Having push working and pull not working is rather unusual. Please send the logs, they could shed some light on the issue you're having.

**Comment by nexxbizdev** [comment] 2019-06-18 07:41
The issues is fixed:
Due to previous issues the CVS integration plugin was still disabled, this was causing random issues with Fetch and Pull while push was working fine.

Now both CVS and Azure DevOps plugins are up-to-date and enabled everything works fine. I'll continue testing and report any issues.

Thanks!

**Comment by ForNeVeR** [comment] 2019-06-18 08:06
Okay, thanks for reporting. Thus closing this issue, because the remaining unsolved parts are essentially a duplicate of #205.

**Closed by ForNeVeR** 2019-06-18 08:06 UTC
Labels: bug
