### ISSUE TITLE
Unusable in existing repositories

### ISSUE THREAD

**Issue by Skyppid** [microsoft/azure-devops-intellij#398] opened 2020-09-21 08:45 UTC
Plain and simple that. I am currently evaluating Rider as potential IDE since Visual Studio is just terrible slow. I'm almost convinced, but the lack of Azure DevOps support is a bummer. Sadly this plugin seems more like a premature alpha version than a usable productive plugin.

I opened our solution which is hosted on DevOps and I simply can't push to Git. I need to enter a password for `{organization}@vs-ssh.visualstudio.com` which obviously isn't the normal account password. I don't know where I'd get that anyway since I expected this plugin to do the authorization. Obviously not. I can only sign in whene cloning a repository which I don't need since I already have it there. In the settings I have a list which is empty and where I can't "update credentials".

Luckily we still got GitKraken, so I can continue working. But functionality wise this is highly questionable. I thought Microsoft teams knew the importance of Usability.

Why is there no sign in button in the settings of that plugin? Why doesn't it recognize that my Git remote is a valid DevOps Git repository? The documentation is only about cloning if there isn't a 404 page missing error.

**Comment by ForNeVeR** [comment] 2020-09-21 09:28
I believe, this is a duplicate of #176: for some reason, the plugin doesn't work for repos set up via SSH.

**Closed** 2020-09-21 09:29 UTC
