### ISSUE TITLE
Incorrect decoding utf-8 text with russian symbols when reading remote files

### ISSUE THREAD

**Issue by yudakov** [microsoft/azure-devops-intellij#416] opened 2021-01-02 17:12 UTC
When plugin is reading remote text files, there are some utf-8 decoding issues with russian symbols (see screenshot).

Remote file (was read incorrectly) is on the left. Local file (correct) is on the right. These files are binary equal.
![image](https://user-images.githubusercontent.com/5665991/103462560-779d2d80-4d3f-11eb-8dca-c9b4177d2571.png)

**Comment by ForNeVeR** [comment] 2021-01-03 04:53
Most likely, this is a duplicate of #311. Let's check again after the fix is applied.

**Closed by ForNeVeR** 2021-01-03 04:53 UTC
