### ISSUE TITLE
Prompted for new OAuth dialog, after already login in

### ISSUE THREAD

**Issue by ericvanwijk** [Microsoft/azure-devops-intellij#178] opened 2018-11-13 15:10 UTC
I try to clone MyShuttle2 as per description here:
https://azuredevopslabs.com/labs/java/intellijgit/

I can successfully log in to my Azure DevOps accounts to browse projects. However, when I try to clone, I get prompted for credentials again, and again after entering the correct ones. I tried two Azure DevOps accounts (a work and school account, and a Microsoft account).

**Comment by mashinchi** [comment] 2019-01-02 09:49
We had the same issue, and we solved it by using git credentials on Azure Devops for the project. But now we face another issue, we are not able to create pull request directly from Webstorm. It shows the same OAuth dialog and the same problem.

**Comment by itlackey** [comment] 2019-01-02 17:42
+1 same problem

**Comment by srollinet** [comment] 2019-01-10 09:02
Same problem in Rider 2018.3 with plugin version 1.150

I also tried authentication using the Device flow and the same issue happens. It keep asking for authentication.

This is probably the same issue as #179

**Comment by srollinet** [comment] 2019-01-10 09:18
As a workaround I was able to authenticate using SSH

**Comment by Saurbaum** [comment] 2019-02-27 21:39
I have the same problem on Linux.  Every single time it prompts me to login again.  if I clone and try and use generated git credentials it fails after prompting over and over.

**Comment by dlapi10** [comment] 2019-03-11 19:12
I have the same problem, but also I would like to share some additional information, that might help to resolve it. 

In my azure repository I have https url for git clone something like this: https://{projectname}@dev.azure.com/{projectname}/{project_repo_name}/_git/{project_repo_name}

I had a problem with visual studio with this url, that might be applicable to this situation as well. The point is was that vs code was trying to clone this repository via user {projectname}, which was not correct. I just tried to clone with https://dev.azure.com/... and cloning with username:password. 

I think, after I log in Rider and I can see my repository and try to clone repository, Rider takes same clone url and tries to authenticate me as a {projectname} user, which is not applicable in this situation, because I have totally different user. 

If this is no help, sorry for the long comment :)

**Comment by MrAdam** [comment] 2019-03-19 11:58
I almost gave up on getting it to work, but after re-fetching the project in the "Check out from Version Control" -> "Team Services Git" option on the IDE start page, it worked perfectly for me.

**Comment by ForNeVeR** [comment] 2019-05-03 15:19
Definitely this is a duplicate of #158, too. We're sorry you're experiencing the issue, it will be fixed soon. Closing as a duplicate.

**Closed by ForNeVeR** 2019-05-03 15:19 UTC
