### ISSUE TITLE
Any action leads to KEY_TF_AUTH_FAIL 

### ISSUE THREAD

**Issue by DdarkSideE** [microsoft/azure-devops-intellij#401] opened 2020-09-23 13:27 UTC
Hello,
I use:
1. Azure DevOps 1.160.0 for Rider
2. JetBrains Rider 2020.2.3
    Build #RD-202.7319.2, built on September 17, 2020
    Runtime version: 11.0.8+10-b944.31 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
    .NET Framework 4.0.30319.42000
    Windows 10 10.0
3. Microsoft Visual Studio Team Foundation Server Version 16.131.27701.1

The problem is that I cannot do anything. Any action leads to KEY_TF_AUTH_FAIL:
[Untitled-1.log](https://github.com/microsoft/azure-devops-intellij/files/5268396/Untitled-1.log)

If I go to VCS->TFVC->Manager workspaces I can see the old workspaces that have already been deleted. So I press "reload workplaces" and get "An error occurred: Access denied connecting to TFS server". I updated the credentials using Rider settings.
I have exported company root cert using Rider Settings->Tools->Server Certificates, but it has changed nothing.
A current workspace has been created by previous TFS plugin which is not supported since Rider 2020. Info about the workplace in Visual Studio: 
<details>
<summary>screenshot</summary>

![devenv_Xs1AIXsnJH](https://user-images.githubusercontent.com/3995841/93995623-8b74e300-fd91-11ea-8417-12bc217b6279.png)

</details>

**Comment by ForNeVeR** [comment] 2020-09-23 15:16
Could you please follow the steps described in https://github.com/microsoft/azure-devops-intellij/issues/400#issuecomment-697338603?

**Comment by DdarkSideE** [comment] 2020-09-23 16:33
Well, it turned out that I already did that earlier (I don't remember if it worked that time) so I have already had certs in cacerts. I replaced them but it didn't help.

**Comment by ForNeVeR** [comment] 2020-09-23 16:35
Could you please clarify, in which `cacerts` do you have these certificates?

**Comment by DdarkSideE** [comment] 2020-09-23 16:36
I have it here: `C:\Program Files\JetBrains\JetBrains Rider 2019.2\jbr\lib\security`

**Comment by ForNeVeR** [comment] 2020-09-24 07:36
After a private discussion with @DdarkSideE, we've been able to find the likely reason for the issue and found a workaround.

Currently I think this is a duplicate of #256, so I'll write a workaround there, and close this.

**Closed by ForNeVeR** 2020-09-24 07:36 UTC
Labels: bug
