### ISSUE TITLE
Plugin crashes when trying to commit

### ISSUE THREAD

**Issue by James-Parsons** [microsoft/azure-devops-intellij#119] opened 2017-11-27 15:56 UTC
I've been using the plugin with PHPStorm for the past few month's and it's starting to completely break. Initially, trying to commit my code give's me a vague and useless "unknown error"

![image](https://user-images.githubusercontent.com/4138815/33275749-95b0ce68-d361-11e7-94d7-0a253dab63c4.png)

Later, after trying to commit again, it appeared it had worked (i.e. now errors) and went about my work. However, it apparently was stuck still trying to commit which blocked PHPStorm from saving files to the file system and I lost two hours of work.

OS: Windows 10 64bit
PHPStorm: 2017.2.4
Plugin Version: 1.125.0

**Comment by ForNeVeR** [comment] 2019-09-05 07:43
Sorry for the long pause. Most likely, this issue is a duplicate of #240, so I'll close it.

In case anyone have the same issues, please examine the IDE log files after that happens. The logs usually contain useful information on the issues like this one.

**Closed by ForNeVeR** 2019-09-05 07:43 UTC
