### ISSUE TITLE
Version control: processing changed files operation performs indefinitely

### ISSUE THREAD

**Issue by streamstr** [microsoft/azure-devops-intellij#364] opened 2020-06-22 15:22 UTC
Recently updated plugin to version 1.160. Now when I execute Move To Another File refactoring in Rider, the VCS operation performs indefinitely:
![image](https://user-images.githubusercontent.com/9412086/85304427-6af86c80-b4b4-11ea-81fc-e966a1dc9f64.png)

For issue reproduction:

1. Create class (i.e. test)
2. Create another class inside same cs file (i.e. test1)
3. Put cursor on second class, press Alt+Enter, choose Move to another file refactoring
4. Bingo

I've noticed that this behaviour is only during Movfe to another file refactoring. When I add manually new file (Alt+Ins) - operation performs as slow, as always, but at least it finishes for 15-20 seconds.

I wrote this ticket and operation is still performing. It cannot be aborted - cancel button does nothing. With this bug I no more can work in Rider - the simpliest and often operation could not be performed. In previous version of plugin this refactoring worked.

**Comment by ForNeVeR** [comment] 2020-06-23 07:35
Could you please upload IDE logs?

**Comment by streamstr** [comment] 2020-06-23 15:24
[rider-logs-20200623-181508.zip](https://github.com/microsoft/azure-devops-intellij/files/4820326/rider-logs-20200623-181508.zip)
Here are logs. Strange, but today I cant reproduce issue. Yesterday I tried several times and every time there was this issue. I not rebooted PC, does nothing special. Hope logs will contain some yesterday info, that might help to find what is causing issue.

**Comment by ForNeVeR** [comment] 2020-06-24 10:26
From the logs, it is still unclear what exactly is happening, but for now it is possible. Some refactorings in Rider (the ones that are coupled with file system operations) may be sensitive to extremely long VCS operations (say, 20-30 seconds), and may time out and break. We're planning to improve file addition performance in one of the next releases.

For now, I think this issue should be closed as a duplicate of #338 (it looks like the plugin tries to execute `tf add` after you extract something from your file, and this operation is known to be slow).

**Closed by ForNeVeR** 2020-06-24 10:26 UTC
Labels: bug, under-investigation
