### ISSUE TITLE
Visual studio team service plugin authentication problem in Intellij

### ISSUE THREAD

**Issue by MDindar** [Microsoft/azure-devops-intellij#179] opened 2018-11-15 20:31 UTC
I've installed Lates version of IntelliJ 2018.2.6 and  Git-2.19.1-64-bit and Visual Studio team Service plugin version 1.15.0  installed on my windows 10.
Whenever I try to import my project to AzureDevOps repository it  prompts and asks me to enter my credential and although it successfully log in, again it asks me to enter my credentials again constantly.
When I check my account in AzureDevOps I can see it created a token for it.
I notice some user suggest to useDeviceFlow, But still no success. after getting the security code, constantly it askes me to enter the new security code again.
Here is the error message on my IDE:
getAuthenticationInfoAsync failed

com.microsoft.alm.plugin.exceptions.TeamServicesException: KEY_VSO_AUTH_FAILED
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:98)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:69)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.idea.git.extensions.TfGitHttpAuthDataProvider.getAuthData(TfGitHttpAuthDataProvider.java:39)
	at git4idea.remote.GitHttpAuthDataProvider.getAuthData(GitHttpAuthDataProvider.java:41)
	at git4idea.remote.GitHttpAuthDataProvider.getAuthData(GitHttpAuthDataProvider.java:36)
	at git4idea.commands.GitHttpGuiAuthenticator$ExtensionAdapterProvider.getDataForUser(GitHttpGuiAuthenticator.java:247)
	at git4idea.commands.GitHttpGuiAuthenticator.askPassword(GitHttpGuiAuthenticator.java:101)
	at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.askPassword(GitHttpAuthService.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.ide.XmlRpcServerImpl.invoke(XmlRpcServerImpl.java:180)
	at org.jetbrains.ide.XmlRpcServerImpl.invokeHandler(XmlRpcServerImpl.java:141)
	at org.jetbrains.ide.XmlRpcServerImpl.process(XmlRpcServerImpl.java:101)
	at org.jetbrains.ide.XmlRpcServerImpl$XmlRpcRequestHandler.process(XmlRpcServerImpl.java:58)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:42)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:57)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:139)
	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:86)
	at org.jetbrains.io.Decoder.channelRead(Decoder.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MDindar** [comment] 2018-11-22 20:15
For those who have the same problem. I tried 1.134.0 version and there is no such that problem.

**Comment by bpaczkowski** [comment] 2018-11-23 16:53
Same issue, on 1.134.0 as well.

**Comment by kodmis** [comment] 2018-11-28 07:58
The same issue 
I've installed version of IntelliJ 2018.1 and Git-2.15.1 and Visual Studio team Service plugin version 1.15.0 installed on my windows 10.

**Comment by MDindar** [comment] 2018-11-28 08:18
> Same issue, on 1.134.0 as well.
Please try PAT instead of a regular password.

**Comment by MDindar** [comment] 2018-12-01 16:19
> > > Same issue, on 1.134.0 as well.
> > 
> > 
> > Please try PAT instead of a regular password. This way worked for me.
> 
> How do I do that? Clicking the icon in the right bottom corner only lets me login with regular credentials (email/password).

I meant try to login to your account via web browser and create a token.  the path for token creation is like this : 
https://dev.azure.com/YourOrganization/_usersSettings/tokens

After that store your token some where and whenever the IDE asked for password, past token instead of regular password

**Comment by bpaczkowski** [comment] 2018-12-12 20:45
That doesn't work for me, after entering my email it redirects me to my organizations login page. There only my regular password works, access tokens and alternate credentials do not.

**Comment by itlackey** [comment] 2019-01-02 17:43
+1 same problem

**Comment by baalthazaar1** [comment] 2019-05-03 14:11
+1 same problem

**Comment by ForNeVeR** [comment] 2019-05-03 15:18
Hey, guys, it is likely a duplicate of #158. We're working on a solution right now!

I'll close it as a duplicate for now.

**Closed by ForNeVeR** 2019-05-03 15:18 UTC
