### ISSUE TITLE
Unable to Checkout from Azure DevOps TFVC

### ISSUE THREAD

**Issue by magwalls** [microsoft/azure-devops-intellij#252] opened 2019-10-18 11:21 UTC
Trying to test the Rider IDE but having issues checking out anything from Azure DevOps TFVC. 

The login process works fine. I'm connected and are able to login but when I select Create Workspace....
![image](https://user-images.githubusercontent.com/2989331/67090216-cd70ce80-f1a9-11e9-9e4b-4770d780ceab.png)

Following error message comes up. 
![image](https://user-images.githubusercontent.com/2989331/67090265-f002e780-f1a9-11e9-8935-cc3065c00a97.png)

Anyone having an idea of the reason behind this problem? 

Regards
Magnus Wallström

**Comment by ForNeVeR** [comment] 2019-10-18 11:28
@magwalls, hello. This is, inveed, very strange. Could you please collect your IDE logs (**Help → Compress Logs And Show in Explorer**), and send them to `ivan.migalev@jetbrains.com`? Thanks.

**Comment by ForNeVeR** [comment] 2019-10-21 07:27
I can't see anything suspicious in your logs. "The syntax of the command is incorrect" is a message from `cmd`: could it be that something's wrong with the `tf.cmd` script itself?

Could you please try executing `tf.cmd /help` in your command line (preferably in Rider terminal, to use the same set of environment variables)? It is a script path to which you have set up in your IDE settings, here:
![image](https://user-images.githubusercontent.com/92793/67184829-cb5b7980-f40e-11e9-817e-f574fc6f5b9d.png)

**Comment by ForNeVeR** [comment] 2019-10-21 11:16
It could be that the credentials cached for this particular connection use some strange/unusual characters that break something in the TF client command line parser. If that's the case, please try to clear the cached credentials by opening the **Azure DevOps Services / TFS** settings page and removing everything with the **Delete configuration…** button:
![image](https://user-images.githubusercontent.com/92793/67200758-daeaba80-f42e-11e9-8467-cffa73f0e927.png)

**Comment by magwalls** [comment] 2019-10-21 14:43
> I can't see anything suspicious in your logs. "The syntax of the command is incorrect" is a message from `cmd`: could it be that something's wrong with the `tf.cmd` script itself?
> 
> Could you please try executing `tf.cmd /help` in your command line (preferably in Rider terminal, to use the same set of environment variables)? It is a script path to which you have set up in your IDE settings, here:
> ![image](https://user-images.githubusercontent.com/92793/67184829-cb5b7980-f40e-11e9-817e-f574fc6f5b9d.png)

Thank you for investing your time into this Ivan! My fault totally. I didn't read the instructions of how to use the plugin. It turned out that I didn't have Java installed on my computer. After installing Java everything seem to work great!

**Comment by ForNeVeR** [comment] 2019-10-21 15:31
Honestly that's strange. We use our own embedded Java to run the plugin binaries, and from your logs I can see that _some_ of the calls worked.

But, anyway, I'm glad that the situation has been resolved. I won't close the issue yet, because I want to perform a small additional research on how the plugin handles the command line arguments in some cases. Will close it later.

**Comment by magwalls** [comment] 2019-10-21 17:00
Yes, I also assumed that Java wasn't required, other than if you actually were going to contribute in the development of the plugin. 
When I ran the command tf.cmd /help I got this error message
_java is not recognized as an internal or external command_ so that's when I figured that Java was required somehow.

**Comment by ForNeVeR** [comment] 2019-10-22 05:28
Actually, if you have no Java installed system-wide, this is expected (but I've unfortunately forgot to mention it). You then could run something like this (`cmd`):
```
set PATH=C:\Users\%USERNAME%\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\193.4744.92\jbr\bin;%PATH%
tf.cmd
```

(where `…\jbr\bin` points to the Rider installation, here I've used an instance from Toolbox)

It is unusual that you have your issue fixed by installing Java: I can't see how it could have any influence of TF Everywhere client execution when run from IDE.

**Comment by ForNeVeR** [comment] 2019-10-22 07:26
I think I've figured out all the information that has been bothering me.

So, we have two ways of running the TF client: the "fast one" and the "slow one".

In the slow mode, we're passing all the arguments through the client command line (and it breaks for some reason on your machine: probably the credentials themselves are too long which happen sometimes).

In the fast mode, we start the client "worker" process with the only argument `@` which means "read the command line from stdin", and then pass the arguments through stdin, which is probably more reliable.

Good news are that we're going to retire old client soon, and are now working on the new reactive client that will work faster and won't require tedious command line argument parsing routines.

I'll close this issue after we implement the checkout functionality in the reactive client.

For now, your workaround would be to do one of this:
1) open your TFVC settings and press the **Test** button on the client setup page: it should load the client version and will allow it to use the "fast mode" that isn't so bugged
2) always check out the repositories from the already started IDE (e.g. open another TFVC project before checking out a new one): when opening any TFVC project, we cache the client version, too, and will use the "fast mode" for further actions, even for checking out a new project

**Comment by magwalls** [comment] 2019-10-22 07:34
Ok! Looking forward to try the new reactive client :) 

However, I ran into another issue trying to connect to my existing workspace used in Visual Studio where I have mapped the root folder $/ to C:\TFS locally. 

But that probably belongs to a separate issue :) 

I followed the guide from here 
https://rider-support.jetbrains.com/hc/en-us/articles/360000335099-How-to-use-Visual-Studio-s-TFV%D0%A1-local-workspace-in-Rider?flash_digest=c0b1059e560c9fdd30080cfa5e1e6a00c15d733c

But still getting teamProjectName is empty for some reason
![image](https://user-images.githubusercontent.com/2989331/67265506-2b552d00-f4ae-11e9-8820-5b8aacfd1932.png)

**Comment by ForNeVeR** [comment] 2019-10-22 07:40
@magwalls this is definitely a known issue #250 which I've already fixed in the master branch, but we haven't published a new build (yet). I'll try to make the publication faster.

For now, the only workaround is to not do that (i.e. to not map the server root directly).

**Comment by ForNeVeR** [comment] 2020-04-15 05:39
Most likely, this is a duplicate of (more thoroughly investigated recently) issue #323.

**Closed by ForNeVeR** 2020-04-15 05:39 UTC
Labels: bug
