### ISSUE TITLE
Can not sign in

### ISSUE THREAD

**Issue by Eugen-Ask** [microsoft/azure-devops-intellij#340] opened 2020-04-29 02:12 UTC
I'm trying to sign in with corporate account with multifactor "Microsoft Authenticator" iOS app.
![image](https://user-images.githubusercontent.com/17223765/80554305-62644800-89d5-11ea-8f76-5bf697626bed.png)
Tried both authentication methods
![image](https://user-images.githubusercontent.com/17223765/80554430-cdae1a00-89d5-11ea-8320-c9cfc974be8d.png)
No difference. The same error. 
Also push and pull operations doesn't work, When I'm pushing, I'm getting a sign-in popup, passing it successfully, but then it pops up again couple of times (and I have to fill in my creds again), and finally it fails completely with error
```
Update failed
Authentication failed for 'https://microsoft.visualstudio.com/DefaultCollection/$project/_git/$repo/'
```
Everything was working fine yesterday. It suddenly stopped working today. Is there a way to fix it?

**Comment by ForNeVeR** [comment] 2020-04-29 07:07
Could you please show the logs that gets written during the push operation?

Also, could you please explain what's a "corporate account" and how does it work?

Unfortunately, nobody has been able to explain to me how it works and if it's possible for me to get one for testing, that's why this issue still persists: I have no way of reproducing it.

**Comment by ForNeVeR** [comment] 2020-04-29 07:11
I believe this is a duplicate of #239, but _please_ provide a detailed explanation of that "corporate account" business if possible.

**Closed by ForNeVeR** 2020-04-29 07:11 UTC
Labels: duplicate
